#!/bin/sh

# These are the build root policies that Red Hat invokes at the end
# of the %install scriptlet.

# Compress man pages (Red Hat uses GNU gzip)
%{_runtimeprefix}/usr/lib/rpm/brp-compress

# Strip ELF binaries (Red Hat uses GNU binutils).
%{_runtimeprefix}/usr/lib/rpm/brp-strip

# Strip even more sections (Red Hat uses GNU binutils).
%{_runtimeprefix}/usr/lib/rpm/brp-strip-comment-note
